// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Job struct {
	ID          string `json:"ID"`
	UserID      string `json:"UserID"`
	Title       string `json:"Title"`
	Company     string `json:"Company"`
	Position    string `json:"Position"`
	Description string `json:"Description"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
